### ISSUE TITLE
Dockerfile has syntax errors

### ISSUE THREAD

**Issue by akoerner1** [Lichtblick-Suite/lichtblick#300]
**Description**

- Version: master branch
- Platform: linux any
- Data source (e.g. bag file, mcap file, rosbridge, ROS 1/2 native):
n/a

**Steps To Reproduce**
`docker build .`
output: 
```
 => ERROR [build 5/6] RUN yarn install --immutable                                                                                                                                       2.4s
------                                                                                                                                                                                        
 > [build 5/6] RUN yarn install --immutable:                                                                                                                                                  
2.307 Syntax Error: Unexpected identifier                                                                                                                                                     
2.307 (function (exports, require, module, __filename, __dirname) { version https://git-lfs.github.com/spec/v1                                                                                
2.307                                                                       ^^^^^                                                                                                             
2.307                                                                                                                                                                                         
2.307 SyntaxError: Unexpected identifier
2.307     at new Script (node:vm:100:7)
2.307     at NativeCompileCache._moduleCompile (/usr/local/lib/node_modules/corepack/dist/corepack.js:41360:22)
2.307     at Module2._compile (/usr/local/lib/node_modules/corepack/dist/corepack.js:41328:41)
2.307     at Object.Module._extensions..js (node:internal/modules/cjs/loader:1252:10)
2.307     at Module.load (node:internal/modules/cjs/loader:1076:32)
2.307     at Function.Module._load (node:internal/modules/cjs/loader:911:12)
2.307     at Module.require (node:internal/modules/cjs/loader:1100:19)
2.307     at require2 (/usr/local/lib/node_modules/corepack/dist/corepack.js:41313:24)
2.307     at u3 (/root/.cache/node/corepack/yarn/3.6.3/yarn.js:390:12580)
2.307     at mf (/root/.cache/node/corepack/yarn/3.6.3/yarn.js:390:13423)
------
Dockerfile:7
--------------------
   5 |     
   6 |     RUN corepack enable
   7 | >>> RUN yarn install --immutable
   8 |     
   9 |     RUN yarn run web:build:prod
--------------------
ERROR: failed to solve: process "/bin/sh -c yarn install --immutable" did not complete successfully: exit code: 1        
```

**Expected Behavior**
the docker context should build without errors regardless of weather the lfs plugin is installed on my local system.

I recommend adding the following to the Dockerfile
```
# Install git and git-lfs
RUN apt-get update && apt-get install -y git && \
    curl -s https://packagecloud.io/install/repositories/github/git-lfs/script.deb.sh | bash && \
    apt-get install -y git-lfs && \
    git lfs install

...

WORKDIR /src
RUN git lfs pull

```

## Example Dockerfile
```Dockerfile
# Build stage
FROM node:16 AS build

# Install git and git-lfs
RUN apt-get update && apt-get install -y git && \
    curl -s https://packagecloud.io/install/repositories/github/git-lfs/script.deb.sh | bash && \
    apt-get install -y git-lfs && \
    git lfs install

WORKDIR /tmp
RUN git clone https://github.com/Lichtblick-Suite/lichtblick.git
RUN mv /tmp/lichtblick /src

WORKDIR /src
RUN git lfs pull

RUN corepack enable
RUN yarn install

RUN yarn run web:build:prod

# Release stage
FROM caddy:2.5.2-alpine
COPY --from=build /src/web/.webpack ./

EXPOSE 8080

COPY <<EOF /entrypoint.sh
# Optionally override the default layout with one provided via bind mount
mkdir -p /lichtblick
touch /lichtblick/default-layout.json
index_html=\$(cat index.html)
replace_pattern='/*LICHTBLICK_SUITE_DEFAULT_LAYOUT_PLACEHOLDER*/'
replace_value=\$(cat /lichtblick/default-layout.json)
echo "\${index_html/"\$replace_pattern"/\$replace_value}" > index.html

# Continue executing the CMD
exec "\$@"
EOF

ENTRYPOINT ["/bin/sh", "/entrypoint.sh"]
CMD ["caddy", "file-server", "--listen", ":8080"]


```

**Comment by carolinabamorim** [comment]
Hi @akoerner1 
thank you for reaching out.
We will review this issue.

Thank you.

**Comment by aneuwald-ctw** [comment]
@akoerner1 thanks for your input on this topic. It is a valid point, for building an image of our software would be nice to not have any local configuration requirements. Although it is true, our team thinks that cloning the repo inside the Dockerfile doesn't make much sense for our goal.

So we decided to leave Dockerfile as it is and keep the need to configure locally the repo (LFS is not an system modification but a repository configuration, that's why you need to clone again inside it).

Thanks again for your input and don't hesitate to reach out us again if you have any issues!
